### ISSUE TITLE
delete_temporary_files: command not found

### ISSUE THREAD

**Issue by ishandutta2007** [vulgo/webdriver.sh#1]
```
./webdriver.sh: line 95: delete_temporary_files: command not found
Error: Is SIP enabled? (1)
No changes were made
```

Here is my system details
`
$ sw_vers`

> ProductName:	Mac OS X
> ProductVersion:	10.13.1
> BuildVersion:	17B1003
> 
`
$ csrutil status
`
>  System Integrity Protection status: enabled.

**Comment by vulgo** [comment]
Thanks. This script needs System Integrity Protection to be disabled, or at least file system protections to be disabled. If you use the -m option unsigned kexts also need to be allowed. I added this information to the readme.

'delete_temporary_files' is a built in function that hadn't been defined at the time file system permissions were tested. I moved it earlier in the file, but you will still get an error as long as 'csrutil status' is enabled.
