### ISSUE TITLE
Runs on 10.14 Mojave, now wait for drivers from NVIDIA

### ISSUE THREAD

**Issue by madmax2** [vulgo/webdriver.sh#17]
So I am confused by this statement in the changelog
-Runs on 10.14 Mojave, now wait for drivers from NVIDIA

So does this let you install NVIDIA web drivers made for High Sierra on Mojave or not?

If no, then please remove that statement since it would be confusing for many people
who thinks this script would let them install nvidia web drivers on mojave
which currently does not have any mojave nvidia web drivers

**Comment by vulgo** [comment]
Yes it lets you install drivers made for High Sierra on Mojave. But it won't as part of an automated process and i would recommend waiting for Mojave drivers from NVIDIA i.e. before upgrading from macOS 10.13 if you want graphics acceleration.

**Comment by fehmi** [comment]
It is good news! Thanks for the great effort. Is there any clue about when the official mojave driver will be available from NVIDIA?

Thanks again

Cheers

**Comment by vulgo** [comment]
Last year NVIDIA [implied](https://devtalk.nvidia.com/default/topic/1043070/announcements/faq-about-macos-10-14-mojave-nvidia-drivers/) that Apple weren't going to approve any new drivers, also directing further enquiries to Apple's own support site.

**Comment by fehmi** [comment]
So waiting is pointless?

**Comment by madmax2** [comment]
@vulgo can you tell me what commands to use to install in on high sierra nvidia web drivers on mojave?
How well does the driver work on mojave?
In terms of
-reading websites
-viewing images
-watching videos 
-3D acceleration
-2D acceleration

**Comment by madmax2** [comment]
@fehmi 
@vulgo 
seem like it is not so good outcome from this article and a few others I've read

https://www.forbes.com/sites/marcochiappetta/2018/12/11/apple-turns-its-back-on-customers-and-nvidia-with-macos-mojave/#777fc02437e9

https://appleinsider.com/articles/19/01/18/apples-management-doesnt-want-nvidia-support-in-macos-and-thats-a-bad-sign-for-the-mac-pro

If you think about it logically, 
there is no way that nvidia couldn't have made a driver in 6 months time already (also not to mention the mojave beta period when Nvidia would have gotten early access)

Based on how quickly they come out with drivers for High Sierra and Windows OS etc..
there should not be a reason why there is no mojave nvidia drivers going on 6 months now (+ the beta time period)

Only logical conclusion, is apple does not want nvidia drivers on mojave.
Apple does not gain anything by having nvidia drivers on mojave, since they are using AMD now..
and in turn hurts nvidia (by getting more people to move over to AMD).

**Comment by crapthings** [comment]
i have an imac27 mid 2011, my original card 6970m is failed and i've ordered two cards which are alienware 780m and alienware 880m, i wish i can get 880m working so that i can return one of those card.

my current os is latest high sierra, can i use this webdriver to get 880m working?

**Comment by vulgo** [comment]
@madmax2 you might get full resolution, there is no acceleration at all, recommend staying on 10.13. 

List High Sierra drivers on Mojave:

```
webdriver list -a
```
