### ISSUE TITLE
problem with using webdriver.sh

### ISSUE THREAD

**Issue by sakoula** [vulgo/webdriver.sh#2]
Hi,
Sorry for opening the issue here but I am having a problem when using the webdriver.sh 

I am on

* 10.3.3 17D47
* NVIDIA 387.10.10.25.156
* SMBIOS iMac17.1
* CsrActiveConfig 0x67

I installed the 104 driver using the webdriver command:

```
sudo ./webdriver.sh -r
sudo ./webdriver.sh -u https://images.nvidia.com/mac/pkg/378/WebDriver-378.10.10.10.25.104.pkg
sudo ./webdriver.sh -m
```

On reboot it 'hangs' with this [photo](https://www.dropbox.com/s/jtxn2py52kbc5mj/IMG_20180205_085441.jpg?dl=0)

The only way to get back is to boot using the recovery partition and remove the driver manually from /L/E and /S/L/E . 

I know that my problem has something to do with the kext caches but I cannot figure what may be wrong. 

Any idea?

Thanks!

**Comment by vulgo** [comment]
https://www.tonymacx86.com/threads/stuck-on-considerrebuildofprelinkedkernel-com-triggered-rebuild.244664/

**Comment by sakoula** [comment]
Thanks vulgo!

This is not related to webdriver: It turns out that the machine was not stuck. I could ssh successfully into the server.  I am posting more in this thread:

https://www.tonymacx86.com/threads/nvidia-releases-alternate-graphics-drivers-for-macos-high-sierra-10-13-3-387-10-10-10-25.243857/page-32#post-1686518
