### ISSUE TITLE
10.13.3 (unable to detect SIP status)

### ISSUE THREAD

**Issue by qu1gl3s** [vulgo/webdriver.sh#3]
Operating System: macOS 10.13.3
Computer: MacBookPro13,2
GPU: GeForce GTX 970
Version: 1.0.17

When attempting to run the script through sudo escalation or as root, it asks whether I have SIP enabled and fails to continue.

Running `csrutil status`, I'm informed that `System Integrity Protection status: enabled.`

I have cleared, disabled and enabled SIP without success. Any information I could provide to assist with this issue, I'm happy to provide.

**Comment by qu1gl3s** [comment]
Doing some reading of the script, I noticed that your method for testing if SIP is enabled on the device is attempting to `touch` the `/System/` directory.

A method that would most likely be more consistent is running the `csrutil` binary within macOS and parsing your checks on this.

**Comment by vulgo** [comment]
The script only needs file system access. What is the output of ```nvram -p | grep csr-active-config``` after disabling SIP?

**Comment by vulgo** [comment]
The unreleased 1.0.18, while still checking for filesystem access, will do things a different way if restrictions are enabled. But if you want modified drivers to load you'll need to allow unsigned kexts. To allow both: ```csrutil enable --without kext --without fs```

**Comment by vulgo** [comment]
I'm closing this issue as 1.1.0 will allow you to continue without allowing unrestricted filesystem access.
