### ISSUE TITLE
Option to patch build version for NVIDIAEGPUSupport

### ISSUE THREAD

**Issue by pavel-shpilev** [vulgo/webdriver.sh#5]
To enable Nvidia eGPU support on a Mac webdriver is not enough. One also need a compatible version of NVIDIAEGPUSupport (https://github.com/pedroresende/NVIDIAEGPUSupport). I understand that the only thing that changes there is MacOS build version. How difficult would it be to add an option to patch NVIDIAEGPUSupport? Thanks

**Comment by vulgo** [comment]
Hi. The build version in NVIDIAEGPUSupport should be getting updated at the same time as NVDAStartupWeb. The path where the EGPU kext is looked for is ```/Library/Extensions/NVDAEGPUSupport.kext```

Using option ```-m``` you should see something like

```
~ $ webdriver -m
NVDAStartupWeb.kext: 17D76 -> 17D102
NVDAEGPUSupport.kext: 17D76 -> 17D102
Updating caches...
Complete.
```

**Comment by pavel-shpilev** [comment]
Oh, snap. I didn't realise it already does that. My apologies. May be worth README mentioning.
