### ISSUE TITLE
just installed with latest version and I have no driver?

### ISSUE THREAD

**Issue by lolwatpear** [vulgo/webdriver.sh#6]
I just tried the newest version of webdriver.sh, as I just reinstalled OSX.  I used an older version for 10.13.3 not too long ago and had no issue.  After this install, I noticed I had no          <key>NvidiaWeb</key> under my clover config.  I added it, and then restarted and realized there's no nvidia manager under system preferences.  It seems like there's absolutely no driver installed at all.  Then I tried running webdriver.sh again, and it's telling me that it's ALREADY installed.  Can you please tell me what is wrong?

**Comment by vulgo** [comment]
Regarding the Nvidia Manager, webdriver.sh doesn't install it. In most cases its only function is to tell you to update when a driver version stops working. Can you confirm whether or not the web driver is accelerating graphics with this command:

```ioreg -n nvAccelerator -r -d 1 | grep -i web```

**Comment by lolwatpear** [comment]
Sorry, I forgot your driver install doesn't do that.  When I put that in terminal, nothing comes up at all.

**Comment by vulgo** [comment]
Yes it sounds like the driver is installed but it isn't starting. A couple of things:

- Clover: remove nv_disable=1 if present in boot flags
- Clover: make sure EmuVariableUEFI + RC scripts are installed if using emulated NVRAM (or use either AptioMemoryFix or OsxAptioFixDrv3 instead)
- Clover: CsrActiveConfig use a permissive value like 0x67 or 0x3FF
- be sure the prelinked kernel is getting rebuilt properly and the web drivers are included, check with ```sudo kextcache -i /``` kext allowed warnings are ok when running this command

**Comment by lolwatpear** [comment]
Ok, so for your last bullet, it seems there's no kext related to Nvidia:

Kext with invalid signatured (-67062) allowed: <OSKext 0x7fefee8083a0 [0x7fff8d703980]> { URL = "FakeSMC.kext/ -- file:///Library/Extensions/", ID = "org.netkas.driver.FakeSMC" }
Kext with invalid signatured (-67062) allowed: <OSKext 0x7fefedf08000 [0x7fff8d703980]> { URL = "USBInjectAll.kext/ -- file:///Library/Extensions/", ID = "com.rehabman.driver.USBInjectAll" }
Kext with invalid signatured (-67062) allowed: <OSKext 0x7fefebdb9d30 [0x7fff8d703980]> { URL = "RealtekRTL8111.kext/ -- file:///Library/Extensions/", ID = "com.insanelymac.RealtekRTL8111" }
KernelCache ID: 659F9AD8412E338AB16AF2F4F5207928
Kext with invalid signatured (-67062) allowed: <OSKext 0x7fce98e72130 [0x7fff8d703980]> { URL = "RealtekRTL8111.kext/ -- file:///Library/Extensions/", ID = "com.insanelymac.RealtekRTL8111" }
Kext with invalid signatured (-67062) allowed: <OSKext 0x7fce98e76d40 [0x7fff8d703980]> { URL = "USBInjectAll.kext/ -- file:///Library/Extensions/", ID = "com.rehabman.driver.USBInjectAll" }
Kext with invalid signatured (-67062) allowed: <OSKext 0x7fce9900a2d0 [0x7fff8d703980]> { URL = "FakeSMC.kext/ -- file:///Library/Extensions/", ID = "org.netkas.driver.FakeSMC" }

**Comment by lolwatpear** [comment]
figured it out:  I didn't have EmuVariableUef.efi under my clover directory.  I don't know why multibeast wasn't installing it, like it did before.  

Sorry for the trouble.  Thanks for your installer, as it's the only way I've been able to get my 4k tv to work at 60hz with cdmi.

**Comment by vulgo** [comment]
No worries. With the majority of hackintosh configurations recent webdriver.sh will patch with Clover so NVDAStartupWeb no longer gets invalidated. Apart from no warning from ```kextcache```, this also means the web driver stays loadable after a macOS update as the dependency on the build number is removed. tonymacx86 do now have Clover packages that don't need/use emulated NVRAM - as the feature isn't in the version in Multibeast yet it's a separate package (there's a script to remove EmuVariableUEFI and associated files as well). Details are [here](https://www.tonymacx86.com/threads/standalone-tonymacx86-clover-builds.245683/) if you're interested.

**Comment by arabesc** [comment]
Clover patch doesn't work for me, web driver isn't loaded.
OSX 10.13.3 (17D102), web driver 378.10.10.10.25.106  17C2205.

**Comment by vulgo** [comment]
@arabesc If you suspect it's an issue with the Clover patch you could run ```webdriver -m``` to patch the driver itself.

**Comment by arabesc** [comment]
Yeah, I know about the -m option. I've just noticed that Clover path doesn't work for some reason, it has been applied, but driver hasn't been loaded. Nvidia control panel writes about wrong version.

**Comment by vulgo** [comment]
@arabesc the Nvidia control panel doesn't work properly with the patch. You can silence its warning with the -m option or uninstall it - it has no effect on the driver loading or not and its update notifications are not that helpful anyway. [This app](https://github.com/vulgo/WebDriverManager/releases) reports accurate driver status and exposes web-driver-related Clover settings in the menu bar.

**Comment by arabesc** [comment]
Interesting. My system was hanging during the boot when only the Clover patch was applied. I was able to boot only with the default macOS graphics driver.

**Comment by vulgo** [comment]
@arabesc could you do ```bdmesg > ~/Desktop/bootlog.txt``` and upload the boot log here?

**Comment by arabesc** [comment]
Do I have to revert the changes from the -m option and enable the Clover patch again?

**Comment by arabesc** [comment]
Here's a current bootlog.
[bootlog.txt.zip](https://github.com/vulgo/webdriver.sh/files/1823108/bootlog.txt.zip)

**Comment by vulgo** [comment]
@arabesc What happens if you leave SIP at 0x3 and run ```webdriver list``` choosing to enable kext patch and reinstalling 378.10.10.10.25.106? Can you reboot like that saving the boot log (F2 at the Clover menu)? Do you reach the login window? Thanks.

**Comment by arabesc** [comment]
The system loads with the default macOS graphics driver, the web driver isn't loaded.
[preboot.log.zip](https://github.com/vulgo/webdriver.sh/files/1827214/preboot.log.zip)

**Comment by vulgo** [comment]
The patch present in the preboot log wasn't added by webdriver.sh. How did you install the script? Homebrew or another way?

**Comment by arabesc** [comment]
I've installed the script with Homebrew and copy-pasted the patch from the clover-patch.plist to my config.plist.

**Comment by vulgo** [comment]
Thanks, somethings not right. Can you confirm you have v1.3.0 with ```webdriver --version``` and that clover-patcher is linked in /etc/webdriver.sh, you can check with ```webdriver --show-settings```.  And can you upload your config.plist here?

**Comment by arabesc** [comment]
```
$ webdriver --version; brew info webdriver.sh
webdriver.sh 1.3.0 Copyright © 2017-2018 vulgo
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
See the GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
vulgo/repo/webdriver.sh: stable 1.3.0
bash script for managing Nvidia web drivers
https://github.com/vulgo/webdriver.sh/
/usr/local/Cellar/webdriver.sh/1.3.0 (6 files, 124.8KB) *
  Built from source on 2018-03-18 at 02:02:24
From: https://github.com/vulgo/homebrew-repo/blob/master/Formula/webdriver.sh.rb
==> Requirements
Required: macOS >= 10.13 ✔
```
`$ webdriver --show-settings` it opens /usr/local/etc/webdriver.sh folder, there is the clover-patcher link that goes to the /usr/local/Cellar/webdriver.sh/1.3.0/libexec/clover-patcher

[config.plist.zip](https://github.com/vulgo/webdriver.sh/files/1832395/config.plist.zip)

**Comment by vulgo** [comment]
Thank you, everything looks good, the patch should be done by Clover when it is enabled in config.plist, webdriver.sh shouldn't be running the patcher automatically. Attached, enabled the Debug key for KernelAndKextPatches, can you confirm that the NVDAStartupWeb binary patch is actually being applied?

**Comment by arabesc** [comment]
The patch is being applied but the Nvidia Web Driver doesn't work after that.
![img_7065](https://user-images.githubusercontent.com/2709027/37738917-9c81aba6-2d69-11e8-9a0f-205790f053b9.jpg)

The Web Driver Manager app shows that Nvidia Web Driver is active.
![screenshot 2018-03-22 00 42 01](https://user-images.githubusercontent.com/2709027/37739019-dba524ca-2d69-11e8-8c0f-8eb747fc88e2.png)
I don't know, may be it's being loaded, but it doesn't work. There is graphics artifacts as if the Default macOS Graphics Driver is working.

```
$ kextstat | grep nvidia
   92    0 0xffffff7f83ab5000 0x3000     0x3000     com.nvidia.NVDAStartupWeb (10.2.9) 1F9F1C91-73DC-3C76-AEB8-96D15E24D548 <12 4 3>
  113    0 0xffffff7f83f19000 0x3000     0x3000     com.apple.nvidia.NVDAStartup (10.2.8) C950F1C2-8619-3966-BAE8-0541B895C0D4 <12 4 3>
  134    0 0xffffff7f842ea000 0x2000     0x2000     com.nvidia.CUDA (1.1.0) 4329B052-6C8A-3900-8E83-744487AEDEF1 <4 1>
```

**Comment by vulgo** [comment]
@arabesc Looks like NVDAStartupWeb is patched and loaded but not starting... I thought the CUDA driver could be involved somehow but it appears the 378* drivers aren't working on 17E182a - no login window with or without CUDA installed (tried last 3 CUDA releases). However 387.* web drivers are working with CUDA + Clover patch on this machine at least.

I'll attach a script to collect some information on the extensions in case anything is not loadable for some reason [info.sh.zip](https://github.com/vulgo/webdriver.sh/files/1836804/info.sh.zip)

If you have modified the build in Info.plist do you also have to disable the kext patch in config.plist to get acceleration or it makes no difference with the modified kext?

**Comment by arabesc** [comment]
I've checked the following configurations:
- Info.plist patch - system boots, web driver works;
- Info.plist + Clover patch - system boots, web driver works;
- Clover patch - system doesn't boot;
- Clover patch + `-v` boot argument - system boots,  web driver doesn't work.

[web_driver.info_patch.txt.zip](https://github.com/vulgo/webdriver.sh/files/1839581/web_driver.info_patch.txt.zip)
[web_driver.info+clover_patch.txt.zip](https://github.com/vulgo/webdriver.sh/files/1839582/web_driver.info.clover_patch.txt.zip)
[default_driver.clover_patch.txt.zip](https://github.com/vulgo/webdriver.sh/files/1839583/default_driver.clover_patch.txt.zip)

**Comment by vulgo** [comment]
@arabesc Thanks, could you try this, booted with filesystem protections disabled, in config.plist change ```CsrActiveConfig``` to ```0x0```, enable the NVDAStartupWeb binary patch. Run these commands
```
webdriver --remove
sudo rm -r /Library/StagedExtensions/Library/Extensions/NVDA*
sudo rm -r /Library/GPUBundles/GeForce*
```
Reboot, then
```
webdriver --list
```
install .106 or .104 driver and reboot.

**Comment by arabesc** [comment]
I've done all of the steps and result is the same - the system doesn't boot and web driver doesn't work without Info.plist patch being applied.

**Comment by vulgo** [comment]
Sorry the steps and other things haven't helped. If possible could you run ```tar -czf ~/Desktop/staged.tar.gz /Library/StagedExtensions/ /Library/GPUBundles``` and upload the archive? Thanks

**Comment by arabesc** [comment]
It's here: [staged.tar.gz](https://www.dropbox.com/s/dkqzj06g6yne4wg/staged.tar.gz?dl=0)

**Comment by vulgo** [comment]
@arabesc the staged bundles look as expected after installing with SIP enabled. What i would expect to be happening after installing like that (csr=0x0) without either Clover patch or Info.plist patch applied, your being able to boot with any SIP configuration and the NVIDIA drivers simply not starting due to NVDARequiredOS.

**Comment by arabesc** [comment]
I'm not sure that I've understood the last message in a right way. Should I do something?

**Comment by vulgo** [comment]
@arabesc From your kextcache output it looks like some kexts were not getting prelinked when the drivers weren't loaded. I added commands to load kexts before caching in recent webdriver.sh, it might help.

**Comment by vulgo** [comment]
@arabesc I've just seen that [NvidiaGraphicsFixup](https://github.com/lvs1974/NvidiaGraphicsFixup) will be patching NVDARequiredOS with the ```-ngfxcompat``` boot argument and also solve the lag problem.
