### ISSUE TITLE
eGPU system crash after entering password on 10.13.4

### ISSUE THREAD

**Issue by akhodakivskiy** [vulgo/webdriver.sh#7]
I was using Sonnet eGPU with nVidia 1080Ti on Mac OS 10.13.3, and everything was working perfectly.
I updated to 10.13.4, and the system started crashing after I enter the password for my account. I just updated webdriver version, but it's still crashing on startup. What can be the problem? Where can I find relevant log files?

**Comment by vulgo** [comment]
Hi. Having only just been released there are new problems with unsupported eGPU hardware on 10.13.4 - simplest solution would be to continue with 10.13.3 until reliable solutions/workarounds become available. Keep an eye on [this thread at egpu.io](https://egpu.io/forums/mac-setup/wip-nvidia-egpu-support-for-high-sierra/paged/38/) for updates on the 10.13.4 situation.

The logs are stored in a [unified logging system](https://developer.apple.com/documentation/os/logging) and can be retrieved with the ```log``` command, see ```man log``` - there are some examples of its use [here](https://eclecticlight.co/2016/10/01/using-the-logs-in-sierra-some-practical-tips/).

**Comment by vulgo** [comment]
Sorry to hear that. I have added a prominent note to the webdriver.sh readme regarding eGPU on 10.13.4. Not much more I can do as it's not an issue with webdriver.sh but with Apple/macOS and their choice not to support our hardware.
