### ISSUE TITLE
Web Interface doesn't work

### ISSUE THREAD

**Issue by Joebeazelman** [vulgo/webdriver.sh#8]
Perhaps, I don’t quite understand how to use it, but command button in the web app gives me an error when I execute it in the terminal:

$ source <(curl -s https://vulgo.github.io/webdriver) 387.10.10.10.30.103
$ (23) Failed writing body

There is also a column for downloading the installer.  What’s the difference?  What does the web application do that webdriver.sh doesn’t do?  Why install the script and all the extra code when I can just download the installer?

**Comment by vulgo** [comment]
The error seems to be caused by github.io not serving the file. If you run the command again it seems to work.

You can read webdriver.sh source and see what it does. With some effort you can see what the NVIDIA installer is doing as well.

**Comment by vulgo** [comment]
@Joebeazelman You are correct the command on the web interface was indeed broken on bash 3. I was seeing the same error message intermittently on a more recent bash version caused (i think) by github.io 'rebuilds', i made some changes that hopefully improve the service. That the command actually works is the main thing though.
